# -*- coding: utf-8 -*-
"""eda_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mRvOVwe5ObYLw_ceNnBNqSA0wABvsI_Q
"""

import pandas as pd

df=pd.read_excel('socialmedia.xlsx')

df.info()

import matplotlib.pyplot as plt
import seaborn as sns

#preview data
df.head()

print(df.shape)

df.isnull().sum().sort_values(ascending=False)

#Engagement Distribution

sns.histplot(df['Likes'],bins=50,kde=True)
plt.xlabel('Likes')
plt.title('Likes Distribution')

plt.show()

#Comments distribution
sns.histplot(df['Comments'],bins=50,kde=True)
plt.xlabel('Comments')
plt.title('Comments Distribution')

plt.show()

#Engagement Distribution

sns.histplot(df['Engagement Rate'],bins=50,kde=True)
plt.xlabel('Engagement Rate')
plt.title('Engagement Rate Distribution')

plt.show()

#Feature Engineering

#1. Post Length

df['post_length']=df['Post Content'].astype(str).str.len()

#2. Check if hashtags are available in content then label as 1

df['has_hashtags']=df['Post Content'].astype(str).str.contains('#').astype(int)


#3. Does the post content have links such as http or 'www'
df['has_links']=df['Post Content'].astype(str).str.contains('http|www').astype(int)

#4. Date features

df['post_hour']=df['Post Timestamp'].dt.hour
df['post_dayofweek']=df['Post Timestamp'].dt.day_name()
df['post_month']=df['Post Timestamp'].dt.month
df['is_weekend']=df['post_dayofweek'].isin(['Saturday','Sunday']).astype(int)

#preview
df[['post_length', 'has_hashtags', 'has_links', 'post_hour', 'post_dayofweek', 'is_weekend']].head()

